### ISSUE TITLE
Unable to advance to Step 5 in IE11

### ISSUE THREAD

**Issue by banteneh** [CityOfBoston/Iterators#166]
Screengrab/videos (insert file names here)
2020 09 01, Unable to advance to Step 5 in IE11.mp4 

Link
https://registry-certs.digital-staging.boston.gov/marriageintention 

Node # (if known) 

Type of User:  Anonymous 
 
Environment
(Device > OS > Browser) 
Computer > Windows 10 > IE11 

Trusted Tester Test 
N/A 
 
Brief Description 
Unable to advance to Step 5 in IE11Unable to advance to Step 5 in IE11err. 

Steps to reproduce 
Not in video: 

1. Go to the Marriage Intention form in both IE11 and Chrome.  Enter identical information into the form fields into both browsers. 

Video starts:  

1. 00:00, Observe, both browser windows display the same page (Step 4 of 6), and have identical information entered.  
2. 00:03, Go to the IE11 window and click on the Next button. 
3. Bug: Observe, the ‘Something went wrong!’ error message appears as a result. 
4. 00:08, Mouse over to the Chrome window and click on the Next button.  Observe, the page advances to Step 5. 
5. 00:12, Still in Chrome, scroll down to the bottom of the page and click Submit.  Observe, the page advances to the final step, (Step 6). 
6. 00:26, Notice, IE11 is still loading (total load time 00:04-01:18), but never advances to the next step. 

Desired Result 
Able to advance to Step 5 in IE11. 
 
Actual Result 
Unable to advance to Step 5 in IE11. 
[2020 09 01, Unable to advance to Step 5 in IE11.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5163209/2020.09.01.Unable.to.advance.to.Step.5.in.IE11.mp4.zip)

**Comment by phillipbentonkelly** [comment]
This field is using the HTML5 time input, looks like it's not supported in IE11 so am going to change this to be a regular text field and add validation so only text formatted as time can be entered.

**Comment by andrebtlima** [comment]
@david-iterators @jill-iterators this is ready to retest

**Comment by jill-iterators** [comment]
@andrebtlima This bug did not pass. Ive attached a new bug report and new video


[2020 09 22, Unable to advance to Step 5 in IE11.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5264496/2020.09.22.Unable.to.advance.to.Step.5.in.IE11.mp4.zip)

Screengrab/videos (insert file names here)
2020 09 22, Unable to advance to Step 5 in IE11.mp4

Link
https://registry-certs.digital-staging.boston.gov/marriageintention

Node # (if known)

Type of User:  Anonymous

Environment 
(Device > OS > Browser)
Computer > Windows 10 > IE11

Trusted Tester Test
N/A

Brief Description
Unable to advance to Step 5 in IE11.

Steps to reproduce
1)	00:00, Starting on Step 4 of 6 within the Marriage Intention Application. 
2)	00:03, Scroll down and click on the Next button.
a.	Bug: Observe, the ‘Something went wrong!’ error message appears as a result.

Desired Result
Able to advance to Step 5 in IE11.


Actual Result
Unable to advance to Step 5 in IE11.

**Comment by jill-iterators** [comment]
@andrebtlima I can tell you worked on this, much improved. A couple of issues, take them or leave them. I always look at consistency and how the rest of boston.gov works. The format of the phone number is still incorrect. It should be xxx-xxx-xxxx. instead it's 7814895073 and you can't tell that's a phone number. Also, two different fields (I will attach screen captures) where a negative number value is accepted. One is on the month of birth and there is no reason for a negative number to be allowed. When you get to the botton of the page you cannot move forward without changing the date. The fix is to remove the negative value and only accept whole numbers from 1-12. The third is on the ZIP code, which have some carrots to move the numbers up and down, to increase or decrease the ZIP code. However, the ZIP code also can't be a negative number so that fix is to remove the ability to place a negative number in the field. Otherwise, the app worked very well and  the tester received confirmation emails. This should be all set once the issues I mentioned are resolved. 
<img width="1569" alt="2020-09-25_14-59-19" src="https://user-images.githubusercontent.com/53226162/94306471-029ca980-ff41-11ea-973e-3c748d0e9f73.png">
<img width="1569" alt="2020-09-25_14-50-54" src="https://user-images.githubusercontent.com/53226162/94306479-06303080-ff41-11ea-8b53-15908c5d3a02.png">

**Comment by andrebtlima** [comment]
@jill-iterators we actually broke the phone number and meeting time issues out into independent tickets, one of which we closed because we removed the field entirely. You can see one here:  #173.
