### ISSUE TITLE
2020 09 27 403 Forbidden Error

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#175]
Screengrab/videos (insert file names here)
2020 09 27 403 Forbidden Error.mp4

Link
https://www.boston.gov/departments/registry/how-get-copy-marriage-certificate

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOs 10.15.5 > Chrome 85

Trusted Tester Test
n/a

Brief Description
When using the boston.gov website, encountered a 404 error, no content was available.

Steps to reproduce
1)	00:00, Go the link noted above. 
2)	00:10 Scroll down the page and click on link How to Get Married at City Hall
3)	00:15, 403 Forbitten error. 

Desired Result
•	Able to review steps to getting married at City Hall

Actual Result
•	Unable to review steps to getting married at City Hall

[2020 09 27 403 Forbidden Error.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5288736/2020.09.27.403.Forbidden.Error.mp4.zip)

**Comment by jill-iterators** [comment]
@subaha-cob I found a 403 Forbidden Error on the boston.gov, details in the ticket. I hope you are doing well.

**Comment by reillyzlab** [comment]
This is referring to the suggested content being fed by Bibblio.

Because marriages are not happening at city hall right now we redirected the 'how to get married at boston city hall' page to 'how to get married in boston'. That redirect is working correctly.

However, wondering if we should update bibblio for this - defer to @andrebtlima and @mmcgowanBOS on whether to do this or not.

No development work needed.

**Comment by subaha-cob** [comment]
@jill-iterators this is on the live site. So please test there unless I say otherwise. thanks.

**Comment by ollie-iterators** [comment]
This issue appears to be fixed
