### ISSUE TITLE
Replacing #151, Null Value, Marriage Certificate

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#178]
Hi @reillyzlab 
I looked up this bug report and video. For some reason we cannot find ticket #151 in Git Hub and it seemed easier for me to send you a copy of the original report and to add the video here. I could have sent to you but it's a larger mp4. Let me know if you have questions once reviewed. Thanks much.

_______________________

Screengrab/videos (insert file names here)
2020 08 25, Invalid Null Value.mp4

Link
registry.boston.gov/death

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOs 10.15.5 > Chrome 84

Trusted Tester Test
N/a

Brief Description
Functional bug – when testing for accessibility, came across a null value on a death certificate information. As a suggestion “unknown” would be an appropriate term to use.

Steps to reproduce
1)	00:00, Go to site, using the link provided above.
2)	00:02, Used a common name to test website, in this case, “Patrick Ryan”
3)	00:04, All “Patrick Ryan” names appear in search
4)	00:15, Note that Patrick Ryan (highlighted in red) has a null value for age. This is a content bug as “null” should not be shown. As a suggestion, “unknown” could be used when the age is unavailable.

Desired Result
•	Able to view death certificate information without content error (null.)

Actual Result
•	Unable to view death certificate information without content error (null)

[2020 08 25, Invalid Null Value.mp4 2.zip](https://github.com/CityOfBoston/Iterators/files/5350601/2020.08.25.Invalid.Null.Value.mp4.2.zip)

**Comment by jill-iterators** [comment]
Hi @reillyzlab
I looked up this bug report and video. For some reason we cannot find ticket #151 in Git Hub and it seemed easier for me to send you a copy of the original report and to add the video here. I could have sent to you but it's a larger mp4. Let me know if you have questions once reviewed. Thanks much.

**Comment by reillyzlab** [comment]
Will need developer to verify why this is happening.

**Comment by reillyzlab** [comment]
@mmcgowanBOS or @phillipbentonkelly can you provide insight?

**Comment by phillipbentonkelly** [comment]
@mmcgowanBOS, @reillyzlab 
I found it, https://registry.boston.gov/death?q=kilpatrick
We should not display the age field if its missing either birth or death date. Leave it up to you to prioritize.

**Comment by reillyzlab** [comment]
@phillipbentonkelly to check and see if there's a way to tell (Via the DB) how many records this applies to.

If number is fairly low, then it might be better for us to have Patty/her staff update the records.

**Comment by phillipbentonkelly** [comment]
@reillyzlab, @mmcgowanBOS, @jimmurphy-boston 

Following up on how many records have this problem; I search the DB table for columns with `null`/no value for the column that saves this and there were not. Interestingly enough that column, `AgeOrDateOfBirth`, is not a date field but rather a string field because they are either entering the date of birth, age, or an age estimate like `3yrs 2months` (pulling my hair emoji) ... It looks like the default value they are using is '000', so looking up how many of those records there are gives us 25k. I'll leave it up to y'all how you want to proceed or comm with Patty. 

I'll fix the front end to not display the 'Age' label/value if it's null; this should close this issue. If we decide that we want to do more than that we should open up a new ticket/issue for that work.

<img width="331" alt="Screen Shot 2021-01-07 at 12 35 54 PM" src="https://user-images.githubusercontent.com/2627273/103926266-aec86180-50e6-11eb-933e-336cf90c7758.png">


Phill

**Comment by phillipbentonkelly** [comment]
The fix is on [staging](https://registry-certs.digital-staging.boston.gov/death?q=Patrick%20WALSH&page=3), check the `Patrick Walk Died: 02/16/1958`. It won't show the `Age` label and when you click to view its details it won't show the date of birth in there either.

**Comment by jimmurphy-boston** [comment]
Correct it is not showing the age.

**Comment by phillipbentonkelly** [comment]
Deployed, [live](https://registry.boston.gov/death?q=PATRICK%20WALSH&page=3)
