### ISSUE TITLE
When the menu button is tabbed over, it expands or contracts the sidebar menu

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#206]
Screengrab/videos (insert file names here)
2020 11 11, Tabbing over menu button causes it to expand or contract.mp4
[2020 11 11, Tabbing over menu button causes it to expand or contract.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5525031/2020.11.11.Tabbing.over.menu.button.causes.it.to.expand.or.contract.mp4.zip)

Link
https://d8-stg.boston.gov/

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.7 > Chrome 86

Trusted Tester Test
Links

Brief Description
When the menu button is tabbed over, it expands or contracts the sidebar menu

Steps to reproduce
1)	00:00, Load the URL, start tabbing through the elements on the page
2)	00:04, The Menu button is tabbed to the first time. Tabbing from it causes the sidebar to be closed
3)	00:07, The Menu button is tabbed to the second time by going backwards (Shift + Tab)
4)	00:08, Tabbing forwards causes the sidebar menu to expand despite not tabbing to the sidebar menu

Desired Result
•	The sidebar menu’s process of expanding and closing works as expected for tabbing through the elements

Actual Result
•	The sidebar menu expands when it is not getting tabbed to, like when you are on the menu and tab forwards instead of backwards

**Comment by subaha-cob** [comment]
@andrebtlima I didn't see the bug report you wanted to add to this ticket.

**Comment by andrebtlima** [comment]
Found several issues:


1.) When a user tabs to the hamburger menu button and presses enter, the hamburger menu opens. If the user does not close the menu, and then continues tabbing through content on the page, beginning with elements in the header, the hamburger menu closes initially, but once the user tabs to the main content of the page and the page begins to scroll, the site header is shifted to the right as if the hamburger menu is open.

Expected behavior: If the user tabs away from the hamburger menu, the hamburger menu should fully close automatically.

https://drive.google.com/file/d/1YxR_jxAq4lKaQEOyRago1vN8ezuoDHyi/view

2.) When a user tabs to the hamburger menu button, open the menu, and continues to use the tab button to navigate, the focus advances to elements in the header, rather than those in the menu. Once the hamburger menu is open, the focus should advance to the first option of the menu when the user uses the Tab button. Currently, the user has to use Shift+Tab access elements in the menu, starting from the bottom of the menu. 

Expected behavior: The keyboard focus should advance such that after a user opens the hamburger menu, the next element highlighted is the first option in the menu.

https://drive.google.com/file/d/133FT1ZWwTcg60Yg-MmyHc2tuLkLQRfeV/view

**Comment by andrebtlima** [comment]
Ok @subaha-cob this looks good to deploy

**Comment by subaha-cob** [comment]
@andrebtlima this will affect any website that uses patterns. Did you create a change management ticket for this already?

**Comment by andrebtlima** [comment]
Change moratorium ends tomorrow so earliest we could make the change is tomorrow. Reilly and I are still figuring out how change management for Digital updates is going to work in Jeanethe's absence so I'm going to suggest we do this at the beginning of next week, since I can't put the change in until that's settled
