### ISSUE TITLE
Not all footer links in Dupral 8 site go to Dupral 8 site

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#29]
Screengrab/videos (insert file names here)
2019 08 15, Not all footer links in Dupral 8 site go to Dupral 8 site.mp4
[2019 08 15, Not all footer links in Dupral 8 site go to Dupral 8 site.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3506009/2019.08.15.Not.all.footer.links.in.Dupral.8.site.go.to.Dupral.8.site.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/45361

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Dupral 8 page > Footer > Footer links

Brief Description
The footer links on the Dupral 8 site do not always go to the Dupral 8 site

Steps to reproduce
1. Open a Dupral 8 page
2. Scroll down to the footer
3. Check out the footer links

Desired Result
•	All of the footer links go to the Dupral 8 site

Actual Result
•	‘Contact Us’, ‘Public Records Requests’ and ‘Report An Issue’ links do not go to the Dupral 8 page

**Comment by davidrkupton** [comment]
Similar to #26, this is because of settings in the current D7 site. These menu links are hardlinked to an "external" site rather than to an internal site.
When the site actually goes live, these links would in fact work because the domain would be https://boston.gov.
However I have changed these to be relative links on the live site, so after the next migration hopefully the links will point to the pages on the site and not hard back to boston.gov.
