### ISSUE TITLE
There are differences in Events on the Public Notices page on Dupral 8 vs Dupral 7

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#44]
Screengrab/videos (insert file names here)
2019 08 19, Differences in Events on Dupral 8 vs Dupral 7.mp4
[2019 08 19, Differences in Events on Dupral 8 vs Dupral 7.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3516260/2019.08.19.Differences.in.Events.on.Dupral.8.vs.Dupral.7.mp4.zip)

Link and Node #
Dupral 8 Link:
- http://bostond8stg.prod.acquia-sites.com/node/59766 
- http://bostond8stg.prod.acquia-sites.com/node/48276

Dupral 7 Link:
- https://boston.gov/node/59766 
- https://boston.gov/node/48276

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Chrome 76

Section
(Page > Area > Element)
Public Notices > Event > Elements

Brief Description
There are differences in the content of the event on the Dupral 8 page vs the Dupral 7 page

Steps to reproduce
1. Go to Dupral 7 and Dupral 8 pages for node 59766 or 48276 page (Video is about node 59766 page)
2. Check out the differences between the events on both pages

Desired Result
•	There are no differences in the content between the Dupral 8 and Dupral 7 page

Actual Result
On the Dupral 8 page:
•	The time is reversed
•	The Neighborhoods section is not in the events section
•	The posted time is in military time (17:51 PM) instead of regular time (2:51 PM)
•	The posted time is one minute different than the time on Dupral 7. 17:51 or 2:51 PM, instead of 2:52 PM
•	The address is different:
o	Dupral 8:
	2300 WASHINGTON STREET
	SCHOOL COMMITTEE CHAMBER, 2ND FLOOR
	BOSTON , MA  02119
	UNITED STATES
o	Dupral 7:
	BRUCE C. BOLLING MUNICIPAL BUILDING
	2300 WASHINGTON STREET
	SCHOOL COMMITTEE CHAMBER, 2ND FLOOR
	BOSTON, MA 02119

**Comment by jimafisk** [comment]
Sidebar Updates:
- [x] The start and end time is reversed
- [x] The Neighborhoods section is missing
- [x] The posted time is using the wrong date
- [x] The posted time is in military time (17:51 PM) instead of regular time (2:51 PM)
- [ ] The posted time is one minute different than the time on Dupral 7. 17:51 or 2:51 PM, instead of 2:52 PM
- [x] The address is different:
  - [x] Remove country in D8
  - [x] Add Name of location in D8
  - [x] Fix comma spacing after city

**Comment by jimafisk** [comment]
@davidrkupton I needed to add `field_multiple_neighborhoods` (label: Related Neighborhoods) to public notices. This field is only used in the sidebar and is not considered in related content logic despite its name. Just wanted to flag to you in case it impacts data migration.

**Comment by ollie-iterators** [comment]
Now the two node sites have been updated at different times so more of the information is different

**Comment by ollie-iterators** [comment]
Nodes do not exist on the Drupal 8 page

**Comment by jimafisk** [comment]
Ok I see. @davidrkupton are we running the migrations against an older snapshot of the database? It looks like the nodes have diverged a bit. 

The only structural issue I see is with "Discussion Topics" on `/public-notices/48276`, they don't seem to get the number styling seen in D7:

<details>
<summary>D7 screenshot</summary>

![d7_dt](https://user-images.githubusercontent.com/5913244/65443756-ac140100-ddfc-11e9-855e-65675ca65561.png)

</details>

<details>
<summary>D8 screenshot</summary>

![d8_dt](https://user-images.githubusercontent.com/5913244/65443764-afa78800-ddfc-11e9-8961-def465da0680.png)

</details>

I'll take care of this.

**Comment by jimafisk** [comment]
Looks like this also has a data migration issue. The discussion topic items are getting saved in the body field of the `public_notice` instead of `field_drawer`:

<details>
<summary>Edit on D7</summary>

![dt_edit_d7](https://user-images.githubusercontent.com/5913244/65446026-77ef0f00-de01-11e9-800e-dcaae9542a13.png)

</details>

<details>
<summary>Edit on D8</summary>

![dt_edit](https://user-images.githubusercontent.com/5913244/65446034-7c1b2c80-de01-11e9-9f2b-9da9bf8e41e8.png)


</details>

**Comment by jimafisk** [comment]
So `field_drawer` seems to work ok: 

<details>
<summary>Screenshot from D8</summary>

![working_dt_d8](https://user-images.githubusercontent.com/5913244/65451314-ea192100-de0c-11e9-9b71-47268b1dfc64.png)

</details>

So we just need to fix the data migration.

**Comment by jimafisk** [comment]
@davidrkupton and I discussed via slack, it's strange that this would be happening during the data migration. I checked through a couple dozen other `public_notice` nodes and it seems like the `field_drawer` data is coming over fine. Let's just keep an eye on http://bostond8stg.prod.acquia-sites.com/public-notices/48276 and potentially fix manually. I'm going to close this ticket because otherwise seems fine to me. 

cc @mmcgowanBOS
