### ISSUE TITLE
The Score absent from Cityscore

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#53]
Screengrab/videos (insert file names here)
2019 08 19 The Score absent from Cityscore.mp4

Link
~http://bostond8stg.prod.acquia-sites.com/departments/transportation~
http://bostond8stg.prod.acquia-sites.com/cityscore

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Chrome 76

Section
(Page > Area > Element)
Cityscore page > Body > The Score

Brief Description
On the Drupal 7 Cityscore page, “The Score” is a key component. It is entirely absent from the Drupal 8 page.
 Steps to reproduce
1.	Go to the Cityscore page
2.	Scroll down in search of The Score

Desired Result
If it’s not exactly where it appears in the D7 build, The Score appears elsewhere on the page.

Actual Result The Score is absent from the D8 page entirely.

[2019 08 19 The Score absent from Cityscore.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3517444/2019.08.19.The.Score.absent.from.Cityscore.mp4.zip)

**Comment by davidrkupton** [comment]
OK this page is populated using data pushed from our "data department".  Because that is not happening to the test area, there is no data on this environment.

I will set up the migration to take the latest data from the D7 environment during migrations, and once done mark this for re-testing.

**NOTE:  doing this will provide data and fix the fact that the component is not showing on the D8 page, however, because the updates are not being pushed, the data in the test environment will quickly become out-of date. Expect future testing to observe numeric differences for city score between D8 and D7.**

**Comment by davidrkupton** [comment]
Done.

**Comment by taylor-iterators** [comment]
Verified. Closing this one.
