### ISSUE TITLE
Pay and Apply damaged links

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#69]
Screengrab/videos (insert file names here)
2019 08 20 Pay and Apply damaged links.mp4

Link
http://bostond8stg.prod.acquia-sites.com/pay-and-apply
http://bostond8stg.prod.acquia-sites.com/node/32906

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Pay and Apply > Main Transactions > Links

Brief Description
On the Pay and Apply page, below the internal Search function is “Main Transactions”; clicking on a transaction brings the user to a bare-bones page that’s clearly unwell.
 Steps to reproduce
1.	Go to the Pay and Apply page
2.	Scroll down to Main Transactions
3.	Click on a transaction link

Desired Result
Page loads without incident.

Actual Result
The page loads, but all such pages are identical and have extremely limited content and functionality.

[2019 08 20 Pay and Apply damaged links.zip](https://github.com/CityOfBoston/Iterators/files/3522233/2019.08.20.Pay.and.Apply.damaged.links.zip)

**Comment by mmcgowanBOS** [comment]
I reviewed this and it seems to that Transaction links are broken and pointing to pages returning a 404.

**Comment by jimafisk** [comment]
There are a couple of issues going on here.

1. The first is that we're not setting the latest published versions during the migration (this is something @davidrkupton has been working diligently to fix since it happens on certain nodes across the site). The result is that anonymous users see a 404 not found error, but authenticated users can see the node. 
2. The second issue is that the Transaction node display is broken even for authenticated users:

![transaction](https://user-images.githubusercontent.com/5913244/63956398-55611480-ca54-11e9-8827-6c9d526fdfe8.png)

It should look like this:

![transaction_d7](https://user-images.githubusercontent.com/5913244/63956589-b852ab80-ca54-11e9-8181-1529d17be343.png)

**Comment by jimafisk** [comment]
**Update:** Clicking on a link in the `/pay-and-apply` view on D8 takes you to a Transaction node. On D7 it actually takes you to a Script Page node. Transaction nodes actually use [rabbit_hole](https://www.drupal.org/project/rabbit_hole) to send users a 404 (so this does _not_ seem to be a migration issue @davidrkupton). We don't need to update the node templates for Transactions, we need to link the view to the appropriate script_page instead.

**Comment by ollie-iterators** [comment]
[2019 08 30, Pay and Apply Damaged Links.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3560511/2019.08.30.Pay.and.Apply.Damaged.Links.mp4.zip)

This is still a thing on the page

**Comment by ollie-iterators** [comment]
This is fixed
