### ISSUE TITLE
Winter in Boston- Need To Know issues

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#89]
Screengrab/videos (insert file names here)
Winter in Boston- Need To Know issues.mp4

Link
http://bostond8stg.prod.acquia-sites.com/winter-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Winter in Boston > Need To Know > First three links

Brief Description
The Drupal 7 version of the “Need To Know” section of the “Winter in Boston” page includes four links, each appropriately labeled and including a relevant image: “What to do with your car”, “Parking during a snow emergency”, “What to do with your trash”, and “Sign up for snow emergency alerts.” On Drupal 8, the first three of these are all missing labels, and “Parking during a snow emergency” is missing its image. Of the four links, on D8 only “Sign up for snow emergency alerts” works properly (and displays properly)- clicking any of the others opens a new tab with the same URL as the current page (http://bostond8stg.prod.acquia-sites.com/winter-boston).

 Steps to reproduce
1.	Go to Winter in Boston page on both Drupal 7 and 8 sites
2.	On D7, scroll down to “Need to Know” and individually open all four links (they all behave as desired)
3.	Attempt to do the same on D8

Desired Result
All links on D8 version of this section have proper labels and images, and when clicked direct the user to the promised page.

Actual Result
One link is missing its image, and three are missing labels and redirect to the current URL- only “Sign up for snow alerts” exhibits the proper behavior.

[Winter in Boston- Need To Know issues.zip](https://github.com/CityOfBoston/Iterators/files/3607007/Winter.in.Boston-.Need.To.Know.issues.zip)

**Comment by jimafisk** [comment]
This looks good now besides it is still missing the "Icon for plows":

![icon_for_plows](https://user-images.githubusercontent.com/5913244/65536763-07fc8980-ded2-11e9-9121-5c579ef59168.png)

@davidrkupton I'm flagging this to you since you're doing the icons. Most of these are working on the dev site. When I inspect the element most have the actual `<svg>` html on the page, however this one seems to use an `<img>` tag. Do you know what's going on here?

Link: http://bostond8dev.prod.acquia-sites.com/winter-boston

Another example on a different page with the same icon missing: http://bostond8dev.prod.acquia-sites.com/311/what-do-your-trash-when-it-snows

**Comment by reillyzlab** [comment]
No icons are appearing.

**Comment by reillyzlab** [comment]
Appears as if all icons/images on 'transactions' component are not working.

Testing on safari

**Comment by reillyzlab** [comment]
Resolved so closing.
